---
title: La reprise d'emploi est-elle roujours rémunératrice ?
subtitle: Si oui, peut-on parler de trappe ? 
author:
  - name: Guillaume Allègre
    email: guillaume.allegre@sciencespo.fr
    affiliation: OFCE, Sciences Po Paris
    affiliation-url: "http://www.ofce.fr"
  - name: Muriel Pucci
    email: muriel.pucci@gmail.com
    affiliation: OFCE & Paris 1
    affiliation-url: "http://www.ofce.fr"
institution: "Observatoire Français des Conjonctures Économiques"
date: today
date-modified: today
lang: fr
abstract: "bla bla"
citation:
  type: article
  container-title: "Document de travail de l'OFCE n°1/2025"
  url: https://ofce.github.io/repriseemploi
wp: 1/2025
annee: 2025
keywords: [RSA, Prime d'ativité, Smic, Pauvreté, Travail, Trappes à pauvreté]
draft: true
format:
  wp-html: default
  wp-pdf: default

bibliography: WP_RepriseEmploi.bib
editor: visual
---

# Introduction : les objectifs de la lutte contre la pauvreté par l'emploi

Y a-t-il de bonnes raisons de reprendre un emploi payé au salaire minimum quand on touche des prestations sociales ? La question des gains liés à la reprise d'emploi est récurrente dans un contexte où les aides sociales sont critiquées pour leur trop grande générosité et où les politiques de tout bord insistent sur la valeur travail: le travail doit payer. Et bien plus que l'assistance.

C'est ce qu'a encore demandé le Premier ministre le 3 octobre 2024 sur France 2. "Il faut que le travail paie plus que l'addition des allocation" a déclaré Michel Barnier, qui entend lancer le "chantier de l'allocation sociale unique", afin que "cela paye plus de travailler que de ne pas travailler". La stratégie nationale de prévention et de luttre contre la pauvreté (SNPLP), publiée en 2018 est même plus précise, puisqu'un des objectifs, alors assigné au revenu univesel d'activité est de "faire en sorte que le travail paye et qu'il paye de la même façon dans tous les cas".

Un deuxième objectif donné aux politiques de lutte contre la pauvreté est de faire en sorte que le travail sorte de la pauvreté. Cet objectif est inscrit dans la SNPLP (2018) soit "l'engagement d'une politique déterminée de sortie de la pauvreté par le travail". Etre pauvre bien que travailleur, travailleur mais pauvre, est perçu comme une anomalie que les politiques publiques doivent corriger (Allègre, 2024).

Enfin un troisième objectif donné aux politiques de lutte contre la pauvreté est de "garantir un soutien financier aux ménages modestes" (SNPLP). Dans la stratégie de lutte contre la pauvreté, cet objectif est le plus souvent lié aux enfants et aux familles : ". Garantir l'accès de tous les enfants aux biens et aux services essentiels" est un des objectifs ; "La stratégie pauvreté déploiera enfin des mesures concrètes et ancrées dans le quotidien des Français pour réduire les privations." est affirmé dans le chapitre nommé "Garantir au quotidien les droits fondamentaux des enfants". On peut toutefois convenir que "réduire les privations", "garantir les droits fondamentaux" sont des objectifs qui concernent tout le monde, adultes et mineurs. Depuis 1946, le préambule de la Constitution affirme "Tout être humain qui, en raison de son âge, de son état physique ou mental, de la situation économique, se trouve dans l'incapacité de travailler a le droit d'obtenir de la collectivité des moyens convenables d'existence". Ce droit ne dit pas comment ces moyens convenables d'existence sont procurés, en nature (logement, santé, aide alimentaire...) ou en espèces.

La stratégie nationale de lutte contre la pauvreté repose ainsi sur au moins trois objectifs : 1. Faire en sorte que le travail paie ; 2. Faire en sorte que le travail sorte de la pauvreté ; 3. Garantir des besoins essentiels ou minimaux. Les trois prochaines parties évaluent le système actuel par rapport à ces trois objectifs. Enfin, dans une quatrième partie, nous verrons ce qu'il faudrait faire si l'on veut atteindre simultanément ces trois objectifs.

# 1. La reprise d'emploi est toujours rémunératrice, mais pas toujours de la même façon.

La reprise d'emploi est-elle rémunératrice ? Pour répondre à la question de façon concrète, d'évaluer en ce sens le système social et fiscal français en raisonnant sur cas-type. Il s'agit d'illustrer les gains à la reprise d'emploi en prenant des exemples-type de situations de travail et de configuration familiale, et éventuellement de logement (pour calculer les allocations-logement) et de gardes (lorsqu'on calcule des frais de garde éventuelles). Dans ces situations, les gains à la reprise d'emploi, proviennent des salaires perçus et des prestations liés à l'emploi (Prime d'activité). Les "coûts" proviennent de l'augmentation des impôts et cotisations (IR, CSG, cotisations sociales) et de la baisse des prestations sociales (RSA, Allocations logement, allocations familiales, Prime d'activité...). La variable d'intérêt est la variation du revenu disponible des ménages. Le revenu disponible est calculé au niveau des ménages et ne tient pas compte de la répartition interindividuelle des revenus au sein des ménages. Seuls les impôts directs impactent ce revenu disponible : l'analyse ne tient pas compte de la TVA par exemple. L'analyse ne tient pas compte non plus des coûts à la reprise d'emploi en termes de transport ou d'habillement ; ou dans le cas général en termes de garde d'enfant (mais nous proposons un focus sur cette question).

Le cas-type général commenté dans le texte est celui d'un ménage éligible au RSA (l'individu référent est âgé entre 25 et 64 ans, sans droits aux allocations chômage) et aux allocations logement (le ménage est locataire du parc privé, en zone 2 des aides au logement (ville moyenne) pour un loyer égal au loyer plafond. Pour les ménages non éligibles à ces prestations, les aides sont bien moindres, et les gains à la reprise d'emploi par construction beaucoup plus importantes. La zone des aides au logement n'a pas une très grande incidence et la plupart des ménages allocataires des aides au logement sont au loyer plafond. Pour les ménages avec enfants, nous supposons dans le cas général deux enfants de 5 à 8 ans mais le focus analyse la situation pour les enfants en bas âge devant être gardés durant la journée. Trois situations de reprise d'emploi au Smic horaire sont analysées : le temps-plein (35 heures hebdomadaires, 1399 euros mensuels) le mi-temps (699 euros). Pour les couples, ces reprises d'emploi sont analysées pour un conjoint inactif et un conjoint à temps-plein. L'analyse n'est pas genrées, mais chez les couples, ce sont le plus souvent les femmes qui prennent des emplois à mi-temps, à la fois parce qu'elles ont tendance à plus s'occuper des charges familiales, et aussi parce qu'elles ont des emplois dans des secteurs où elles plus sont plus susceptibles d'être en temps-partiel subi. L'analyse est descriptive et ne présume pas que les ménages ou individus ont le choix entre les différentes combinaisons de travail. Comme son nom l'indique le salaire minimum constitue un plancher. 85% des salariés ont un salaire supérieur, dans ces cas les gains en revenus disponibles - et les écarts de revenu disponible entre les personnes en emploi et les bénéficiaires du RSA - sont plus élevés.

Les graphiques illustrant ces cas-types montrent que le système socio-fiscal actuel garantit que la reprise d'emploi est toujours rémunératrice, mais pas nécessairement toujours dans les mêmes proportions.

Le cas d'une personne seule illustre la façon dont le système socio-fiscal assure que le travail paie mieux que l'assistance, même pour de petites durées de travail. Sans revenus d'activité, cette personne peut percevoir 851 euros de prestations sociales (559 euros de RSA auxquels se cumulent 292 euros d'allocations logement). Son revenu disponible équivaut alors à 39% du niveau de vie médian.

Si cette personne reprend un emploi rémunéré au Smic, son revenu disponible augmente, en dépit de la baisse du montant de prestations sociales, que l'emploi soit à temps partiel ou à temps plein. Avec un emploi à temps-plein, le revenu disponible est de 1656 euros, soit pratiquement le double que sans revenu d'activité, ou un écart de +804 euros. Dans cette situation, taux marginal effectif de prélevement (TMEP) est de 42,5%, ce qui veut direque les ménages gardent en revenu disponible 56,5% de l'augmentation de leurs revenus d'activité (qui correspond au salaire de 1399 euros mensuels dans ce cas).

Pour un couple avec deux enfants, initiatilement sans revenu et dont un des conjoints reprend un emploi à plein-temps, le gain de revenu disponible en euros est de +811 euros, soit un gain très similaire en euros au cas du célibataire sans enfant, et par conséquent un TMEP également similaire (42%). Si le gain en euro est similaire, ce couple a un revenu disponible plus important en situation d'inactivité (1155 euros) donc le gain relatif est moindre. Ce couple a également plus d'unités de consommation, donc le gain en niveau de vie est également moindre (environ deux fois moindre, car le nombre d'uc du couple est de 2.1).

Définition : niveau de vie

:   Le calcul du niveau de vie d'un ménage a pour objet de comparer les revenus disponibles de ménages de configuration différentes en tenant compte des éventuelles économies d'échelle et des besoins moindres des jeunes enfants. Il est obtenu en divisant le revenu disponible de l'ensemble du ménage par un nombre d'unités de consommation. En France et en Europe, les unités de consommation sont calculées par l'INSEE et Eurostat selon l'échelle d'équivalence dite de l'OCDE modifiée qui attribue 1 UC au premier adulte du ménage, 0,5 UC aux autres personnes de 14 ans ou plus et 0,3 UC aux enfants de moins de 14 ans (car considérés ayant moins de besoins).

La situation est un peu différente pour une personne en couple sans enfant si le conjoint est actif en emploi, rémunéré sur la base d'un Smic mensuel. Dans ce cas, la reprise d'emploi est plus rémunératrice car la dégressivité des aides est moindre : alors que le revenu disponible du couple sans enfant est de 1487 euros en cas de monoactivité au Smic, il est de 2797 euros en cas de biactivité, soit un gain de +1310 euros et un taux marginal de prélèvement de seulement 6% (le couple biactif cumule deux bonus individuels de Prime d'activité, ce qui compense la baisse des autres prestations). Pour une reprise à mi-temps (salaire de 699 euros), le gain est de +611 euros (soit un taux marginal de prélèvement de 12%). Pour un salaire de 1,5 Smic (2 098 euros), le gain à la reprise d'emploi est de +1 923 euros, de 8%.

Le même couple, mais avec deux enfants cette fois, est plus aidé en situation de monoactivité (revenu disponible de 1891 euros) et son gain est un peu moindre pour le passage à la biactivité au SMIC (+1090 euros) soit un taux marginal de prélèvement de 22%. A mi-temps le gain est de +497 euros (TMEP de 29%) et pour un salaire de 1,5 SMIC le gain est de +1754 euros (TMEP de 16%).

Le système social et fiscal remplit donc l’objectif qui lui a été fixé depuis la mise en place du RSA en 2009 : rendre le travail plus rémunérateur que l’assistance, de façon pérenne et pour toutes les reprises d'emploi. Toutefois les gains de reprise d'emploi ne sont pas homogènes, ce qui se voit en creux par la forte variabilité des taux marginaux effectifs de prélèvement. Dans les cas que nous avons commenté ici, le taux varie de 6% pour le passage de la monoactivité à la biactivité d'un couple sans enfant, à 42% pour une personne seule passant de l'inactivité à l'activité à temps-plein. Le premier garde ainsi 94% de l'augmentation de ses revenus d'activité et le second 58%. Mais le premier est initialement beaucoup plus pauvre, et donc plus aidé. Le second cumule deux bonus individuels de prime d'activité.

La prime d'activité

:   Depuis le 1er janvier 2016, la Prime d'activité a remplacé le RSA activité et la prime pour l'emploi. Comme les instruments qu'elle remplace, la prime d'activité vise deux objectifs : soutenir l'offre de travail grâce à des incitations financières accrues et compléter les revenus des travailleurs ayant des revenus modestes. La prime pour l'emploi et le RSA activité ont été critiqués pour leur faible efficacité. Individualisée, la prime pour l'emploi versait de faibles montants à de nombreux bénéficiaires : trop faible pour être véritablement incitative, elle bénéficiait de plus à des ménages à niveau de vie intermédiaire et non aux plus modestes. Le RSA activité tenait compte de la composition et
    du revenu du ménage : il était bien ciblé sur les travailleurs pauvres et créait des incitations à la reprise d'emploi substantielles et contemporaines. Néanmoins, son efficacité était minée par un non-recours élevé (68 %).

    La prime d'activité est proche dans son fonctionnement du RSA activité : familialisée, versée mensuellement, après une déclaration trimestrielle de revenus, elle cible les travailleurs aux revenus modestes et conserve les incitations à la reprise d'emploi. Elle est en outre clairement identifiée comme une prestation à destination des personnes exerçant une activité, ce qui évite qu'elle apparaisse stigmatisante aux yeux de ceux qui la perçoivent. Par conséquent, le non-recours (3x%) est bien plus faible que celui qui était observé pour le RSA activité.

    La formule de la prime d’activité est la suivante :

    Prime d’activité du foyer = Montant forfaitaire qui dépend de la situation familiale - (forfait logement + prestations familiales + autres minima sociaux) + bonus d’activité individuels - 39 % des revenus professionnels - 100 % des revenus non professionnels

    Si elle permet de garantir des gains entre inactivité et revenus du travail dans presque toutes les configurations, la prime d'activité a des limites. Par rapport à une hausse du Smic, c'est une prestation sociale et pas un salaire donnant des droits sociaux (chômage, retraites). Comme la formule le montre, les revenus non professionnels du foyer sont déduits à 100%. Dans un couple, si un des conjoints perd son emploi pour du chômage indemnisé, non seulement il perd son bonus d'activité individuel, mais son chômage est déduit de la prime de son conjoint. Par conséquent, dans la plupart des cas, les ménages incluant un chômeur indemnisé (ou un retraité) ne touchent pas de prime d'activité . Enfin, bien que visant à lutter contre les trappes, les compléments de revenus pour travailleurs pauvres sont critiqués par les trappes qu'ils créent (au-dessus) : ciblés sur le temps-partiel, ils créent une trappe à précarité ; ciblés sur le temps-plein, comme la prime d'activité, ils renforcent la trappe à bas-salaire. En matière d'incitations, ces compléments ciblés ne peuvent que creuser un trou pour en reboucher un : si la prime augmente l'écart avec l'inactivité, étant dégressive, elle ne peut que le réduire quelque part plus haut.

# 2. L'emploi ne protège pas toujours de la pauvreté.

Si l'emploi est toujours rémunérateur il ne protège pas toujours de la pauvreté. Ceci peut se voir par cas-type et par l'existence d'une pauvreté en emploi. En 2022, selon l'INSEE le taux de pauvreté sur l'ensemble de la population était de 14,4%. Le taux de pauvreté des personnes en emploi était de 7,7%. L'emploi réduit ainsi beaucoup le risque de pauvreté mais ne l'annule pas : sur les 9,1 millions de personnes pauvres, 2 millions sont en emploi (INSEE).

Définition : pauvreté monétaire

:   D'après la statistique publique (INSEE, Eurostat), un individu est pauvre d'un point de vue monétaire, si le niveau de vie du ménage auquel il appartient est inférieur à 60% du niveau de vie médian. La pauvreté monétaire est ainsi un concept relatif : si le niveau de vie de tous les ménages augmente de 10%, la pauvreté monétaire reste stable. Par convention, le seuil de pauvreté est le même dans tous le pays, mais il varie au sein de l'Union Européenne d'un pays à l'autre. La pauvreté est définie par les revenus. La seule prise en compte des besoins se fait à travers la composition familiale (nombre d'individus et âge des enfants). Le niveau de vie ne prend ainsi pas en compte les besoins différenciés en transport, logement ou chauffage.

    Le dernier seuil de pauvreté publié par l’Insee est de 1216 euros par uc pour l’année 2022. Pour le comparer aux montants des prestations en 2024, nous avons appliqué à ce seuil l’inflation observée entre 2022 et juillet 2024, soit 1309 euros par uc.

Le niveau de vie d'un célibataire sans enfant sans revenu d'activité et recourant à toutes les prestations est de 851 euros/uc ce qui correspond à 65% du seuil de pauvreté. Son intensité de pauvreté, égale à la distance au seuil de pauvreté, est donc de 35%. Un emploi à mi-temps au Smic ne lui permet pas de franchir le seuil de pauvreté (intensité de 9%). Le célibataire sans enfant franchit le seuil de pauvreté avec un Smic à plein temps (126% du seuil).

Une personne isolée avec enfant en emploi à plein-temps au Smic reste au-dessus du seuil, qu'elle ait un enfant (125%) du seuil), deux enfants (119%), ou trois enfants (124%). Le système socio-fiscal maintient ainsi le niveau de vie des personnes isolées lorsqu'elles travaillent au Smic et ont des enfants (un peu moins pour deux enfants).

Les revenus d'un couple monoactif dans lequel un des conjoints travaille au Smic à plein-temps, et l'autre conjoint est en inactivité; permettent tout juste d'atteindre le seuil de pauvreté si le couple n'a pas d'enfant. Dans ce cas, le niveau de vie est égal à 100% du seuil de pauvreté. A ce niveau de revenus, le système social ne compense pas entièrement la charge des enfants, et le niveau des couples monoactifs avec enfants est légèrement plus faible. Ces ménages ont donc des revenus qui les placent sous le seuil de pauvreté, avec un niveau de vie égal à 93% du seuil de pauvreté pour monoactif avec 1 enfant, 91% avec 2 enfants, et 95% avec 3 enfants.

Les couples biactifs au Smic à temps-plein, ayant donc des revenus d'activité équivalent à 2 Smic, ont un revenu disponible qui leur permet d'échapper à la pauvreté. A ce niveau de revenu, le système fiscal et social compense moins la charge des enfants. Un couple biactif au Smic sans enfant a un niveau de vie équivalent à 142% du seuil de pauvreté. Avec un enfant, le niveau de vie descent à 119% du seuil de pauvreté, 108% avec deux enfants et 110% avec trois.

# 3. Le revers des incitations est l'augmentation de l'intensité de la pauvreté.

Le niveau de vie des ménages sans revenus d'activité est faible, et a décru dans le temps. En outre, le niveau du minimum social en direction des personnes d'âge actif a progressé bien moins vite que le niveau du minimum vieillesse (ASPA) ou de l'allocation adulte handicapée.

En 1989, la loi instaurant le RMI a pour principal objectif de donner un minimum social pour les personnes valides d’âge actif. L’objectif est principalement distributif. Il garde néanmoins les incitations en tête en fixant le niveau du RMI par rapport au SMIC à temps plein. Les débats font apparaître la volonté de garder une norme d’emploi à plein- temps. Dans les années 1990, le nombre d’allocataires augmente rapidement et atteint un niveau non anticipé par les décideurs publics : de 500 000 allocataires en 1990, ce nombre dépasse le million en 1996. Face à cette montée rapide, le discours sur les « trappes à pauvreté » se répand. En 2001, l’introduction de la prime pour l’emploi est une première réponse à ce discours. Dans un premier temps, son montant est maximal à temps-plein. La PPE étant accusée d’être mal ciblée, le RSA activité prend la relève en 2009 et permet de garantir que le revenu disponible d’un foyer augmente lorsque ses revenus d’activité augmentent, même à temps partiel ou très partiel. Il est ensuite remplacé par la prime d’activité en 2015, revalorisée lors de la crise des gilets jaunes. Durant cette période d’attention aux gains à l’emploi et à la pauvreté laborieuse, le montant de base du RSA est peu revalorisé.

Pourtant, malgré l’augmentation des gains à la reprise d’emploi via le creusement de l’écart entre le RSA et le SMIC et la montée en charge des compléments de revenus pour travailleurs pauvres, la part d’allocataires du RSA dans la population d’âge actif a augmenté, passant de 3,0% en 2008 à 4,1% en 2022. La réduction du niveau de vie relatif du RSA n’a donc pas eu d’effets visibles en termes de baisse du nombre d’allocataires.

# 4. Que faire si l'on prend la lutte contre la pauvreté au sérieux ?

Le système social et fiscal remplit donc l’objectif qui lui a été fixé depuis la mise en place du RSA en 2009 : rendre le travail plus rémunérateur que l’assistance. Mais avoir un emploi rémunéré au Smic n’est pas un gage de sortie de la pauvreté, et vivre sans emploi implique souvent d’être dans une situation de grande pauvreté. Que faire ?

##4.1. Augmenter le socle

Il est possible de concilier les trois objectifs – travail rémunérateur, travail permettant de sortir de la pauvreté et niveau de vie minimum suffisamment élevé – dans le système actuel d’intéressement de la prime d’activité en relevant le montant des prestations de solidarité (RSA et aides au logement).

Le RSA pourrait être revalorisé de sorte qu’un foyer sans emploi atteigne 50 % du niveau de vie médian, soit 1 090 euros pour une personne isolée sans enfant, et 2 290 euros pour un couple avec deux enfants. Avec les aides au logement actuelles, pour la personne seule vivant en zone 2 (villes de plus de 100 000 habitants), cela amènerait le montant du RSA à 798 euros.

En conservant les incitations actuelles, par alignement du socle de la prime d’activité sur le RSA, cette revalorisation permettrait aux couples avec deux enfants de franchir le seuil de pauvreté monétaire avec un seul emploi au Smic à temps plein.

Dans le système actuel, le travail est plus rémunérateur que l’assistance car la prime d’activité compense le faible niveau du Smic. Si les personnes en emploi restent pauvres malgré les allocations et les incitations… c’est qu’ils partent de trop bas.

##4.2 Le Smic ou la prime d'activité ?

##4.3 Quelle place pour le temps partiel ?

```{r librairies}
#| echo: false

library(ofce)
library()
```
